environment:
  base_box: "centos/7"

boxes:
- name: "node1a"
  swarm_role: "manager"
  mem: "6144"
  cpu: "3"

# - name: "node2"
#   swarm_role: "worker"
#   mem: "1524"
#   cpu: "1"

# - name: "node3"
#   swarm_role: "worker"
#   mem: "1524"
#   cpu: "1"

# - name: "node4"
#   swarm_role: "worker"
#   mem: "1524"
#   cpu: "1"
