environment:
  base_box: "centos/7"

boxes:
- name: "nc-test1"
  mem: "6144"
  cpu: "3"

# - name: "node2"
#   mem: "1524"
#   cpu: "1"

# - name: "node3"
#   mem: "1524"
#   cpu: "1"

# - name: "node4"
#   mem: "1524"
#   cpu: "1"
