---
- name: INSTALL-KIND | Install kind
  get_url:
    url: https://kind.sigs.k8s.io/dl/v0.9.0/kind-linux-amd64
    dest: /usr/local/bin/kind
    mode: "0755"

- name: INSTALL-KIND | copy cluster config
  copy:
    content: |
      # kind cluster config
      kind: Cluster
      apiVersion: kind.x-k8s.io/v1alpha4
      nodes:
      - role: control-plane
      # - role: worker
      # - role: worker
    dest: ~/kind-cluster-config.yml
  become: false

- name: INSTALL-KIND | Check if kind is running
  shell: "docker ps | grep 'kindest/node' | awk '{print $2}' | uniq"
  register: result

- name: INSTALL-KIND | Show result
  debug:
    var: result.stdout_lines

- name: INSTALL-KIND | get my id with newgrp
  shell: "newgrp docker; id"
  register: id_result
  become: false

- name: INSTALL-KIND | show my_id
  debug:
    var: id_result

- name: INSTALL-KIND | create cluster
  shell: "newgrp docker; kind create cluster --config ~/kind-cluster-config.yml"
  become: false
  when: result.stdout_lines is not search('kindest/node') and kind.create_cluster | bool

- name: INSTALL-KIND | Generate kind bash completion  
  shell: kind completion bash > ~/.kind-completion
  become: false
  args:
    creates: ~/.kind-completion

- name: INSTALL-KIND | Add kind bash completion to .bash_profile
  blockinfile:
    path: /home/{{ ansible_user }}/.bash_profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK - KIND"
    block: |
      # Kind shell completion
      source $HOME/.kind-completion
  become: false

# TODO - make handler of it
- name: INSTALL-KIND | Generate kubectl bash completion  
  shell: kubectl completion bash > ~/.kube/completion.bash.inc
  become: false
  args:
    creates: ~/.kube/completion.bash.inc

- name: INSTALL-KIND | Add kubectl bash completion to .bash_profile
  blockinfile:
    path: /home/{{ ansible_user }}/.bash_profile
    block: |
      # Kubectl shell completion
      source $HOME/.kube/completion.bash.inc
  become: false