---
- name: INSTALL-K8s TOOLS | Install buildpacks
  unarchive:
    src: https://github.com/buildpacks/pack/releases/download/v0.15.1/pack-v0.15.1-linux.tgz
    remote_src: yes
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "0755"

- name: INSTALL-K8s TOOLS | Download skaffold
  get_url:
    url: https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
    dest: /home/{{ ansible_user }}/skaffold-linux-amd64
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: false    

- name: INSTALL-K8s TOOLS | Install skaffold
  command: install /home/{{ ansible_user }}/skaffold-linux-amd64 /usr/local/bin/skaffold
  args:
    creates: /usr/local/bin/skaffold    

- name: INSTALL-K8s TOOLS | Install octant
  unarchive:
    src: https://github.com/vmware-tanzu/octant/releases/download/v0.16.3/octant_0.16.3_Linux-64bit.tar.gz
    remote_src: yes
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "0755"
    exclude:
    - README.md
    extra_opts:
    - --strip-components=1
