---
- name: INSTALL-MINIKUBE | Download minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /home/{{ ansible_user }}/minikube-linux-amd64
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: INSTALL-MINIKUBE | Install minikube
  command: install /home/{{ ansible_user }}/minikube-linux-amd64 /usr/local/bin/minikube
  args:
    creates: /usr/local/bin/minikube

# - name: INSTALL-MINIKUBE | Remove installer
#   file: 
#     path: /home/{{ ansible_user }}/minikube-linux-amd64
#     state: absent