---
- name: INSTALL-K8s TOOLS | Check latest kubectl stable version number
  uri:
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    return_content: yes
  register: kubectl_version
  when: k8s_tools.kubectl_install | bool

- name: INSTALL-K8s TOOLS | Show kubectl_version_result.content
  debug:
    var: kubectl_version.content
  when: k8s_tools.kubectl_install | bool    

- name: INSTALL-K8s TOOLS | Install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: "0755"
  when: k8s_tools.kubectl_install | bool

- name: INSTALL-K8s TOOLS | Generate kubectl bash completion  
  shell: kubectl completion bash > ~/.kubectl-completion-bash
  become: false
  args:
    creates: ~/.kubectl-completion-bash
  when: k8s_tools.kubectl_install | bool

- name: INSTALL-K8s TOOLS | Add kubectl bash completion to .bash_profile
  blockinfile:
    path: /home/{{ ansible_user }}/.bash_profile
    block: |
      # Kubectl shell completion
      source $HOME/.kubectl-completion-bash
  become: false
  when: k8s_tools.kubectl_install | bool

- name: INSTALL-K8s TOOLS | Install buildpacks
  unarchive:
    src: https://github.com/buildpacks/pack/releases/download/v0.15.1/pack-v0.15.1-linux.tgz
    remote_src: yes
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "0755"
  when: k8s_tools.pack_install | bool

- name: INSTALL-K8s TOOLS | Download skaffold
  get_url:
    url: https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
    dest: /home/{{ ansible_user }}/skaffold-linux-amd64
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: false
  when: k8s_tools.skaffold_install | bool

- name: INSTALL-K8s TOOLS | Install skaffold
  command: install /home/{{ ansible_user }}/skaffold-linux-amd64 /usr/local/bin/skaffold
  args:
    creates: /usr/local/bin/skaffold
  when: k8s_tools.skaffold_install | bool

- name: INSTALL-K8s TOOLS | Install octant
  unarchive:
    src: https://github.com/vmware-tanzu/octant/releases/download/v0.16.3/octant_0.16.3_Linux-64bit.tar.gz
    remote_src: yes
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "0755"
    exclude:
    - README.md
    extra_opts:
    - --strip-components=1
  when: k8s_tools.octant_install | bool