---
- name: INSTALL-DOCKER | Add docker-ce yum repo
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo     

- name: INSTALL-DOCKER | Install Docker Packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: INSTALL-DOCKER | Enable & Start Docker Service
  service:
    name: docker
    state: started
    enabled: yes

- name: INSTALL-DOCKER | Add user 'vagrant' to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: INSTALL-DOCKER | reset ssh connection to reflect changes for 'currently logged user'
  meta: reset_connection

- name: INSTALL-DOCKER | Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose.version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "0755"

- name: INSTALL-DOCKER | Check latest kubectl stable version number
  uri:
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    return_content: yes
  register: kubectl_version

- name: INSTALL-DOCKER | Show kubectl_version_result.content
  debug:
    var: kubectl_version.content

- name: INSTALL-DOCKER | Install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: "0755"
