---
- name: "Play with manage-k8s-lab role | install k8s local clusters & tools ;)"
  hosts: localhost,all
  become: true
  user: vagrant

  vars:
  - minikube:
      install: false
      start: false
      memory: "4096"
      cpus: "2"
      k8s_version: "1.19.6"

  - kind:
      install: true
      create_cluster: false

  - k8s_tools:
      install: true
      kubectl_install: true
      pack_install: false
      skaffold_install: false
      octant_install: false

  - meshery:
      install: false  

  roles:
    - manage-k8s-lab
